services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: whiteboard
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: whiteboarddb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: